# https://github.com/robherley/go-test-action

name: Test src

on:
  push:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: Learn_Go_With_Tests/src/go.mod

    - name: Build
      run: go build -v ./...

    - name: Test
      uses: robherley/go-test-action@v0
      with:
        moduleDirectory: Learn_Go_With_Tests/src

