# Lint the root directory Go files

name: lint-root

on:
  push:
    branches:
      - main
      - feat-ci
  pull_request:

permissions:
  contents: read

jobs:
  lint-root:
    name: lint root directory
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: golangci-lint root
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1
          working-directory: .
